# 現在與未來

## 科幻小說般的智慧生活型態

　　在科幻電影或小說中，我們總能常看見主角們搭上一輛無人駕駛的交通工具、將視訊影像直接立體投影呈現，或者是運用音控來完成許多大小事等等。不要認為這樣的情節並不會在現實生活出現，現在，這一切就正在我們的生活中，一項一項逐漸成真。

　　最近一兩年來，物聯網IOT（Internet of Things）、人工智慧AI（Artificial Intelligence）、大數據（Big Data）、穿戴型裝置（Wearable device）、自駕車（Self-driving cars）等名詞在臺灣被吵得火火熱熱，無論是在什麼地方、什麼場合，你總是都能聽到這些詞，那麼這些新科技，究竟會對我們的生活帶來多大的影響？讓我們一起試著去想像以下的情境...


一天的開始，早晨和煦的光線從窗外灑進來，此時沉浸在睡意中的你還不想起身離開軟綿綿的床鋪。

：「今天的狀況如何？」

：『現在時間早上八點鐘，26°C天氣晴朗舒適，空氣品質佳。』

：『搭上8:49分的932公車，就能順利趕上您九點半的預定行程。』

：「知道了。」

你爬起身的同時，房間就自動播出你最喜歡的輕音樂，簡單盥洗後你匆匆出門，剛好搭上抵達時間分毫不差的自動駕駛公車，此時新型的智慧手環跳出兩條通知：「浴室燈狀態：ON」，「大門鎖狀態：OPEN」，你按了一下按鈕，便呼叫智慧家居系統將物品狀態全數調整為「出門模式」，你就知道你不用再為家裡繁瑣的事情擔心，放心地在外活動了......。

　因應人類的使用需求，透過物聯網、人工智慧等等新科技，將會生產出越來越多的智慧型物件，在這些新科技不斷地擴大應用面的同時，未來將打造出和如今大不相同的生活型態，人類與機器人的互動將大幅上升，我們的生活會變得更智慧、也更便利。


### 關於智慧生活的有趣小影片 {-}

智慧家居的模樣？  

<iframe width="560" height="315" src="https://www.youtube.com/embed/lOjCN8cSCZ8" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

現在的穿戴式裝置長這樣  

<iframe width="560" height="315" src="https://www.youtube.com/embed/yVWqS1rR9n0" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

什麼是物聯網？ 

<iframe width="560" height="315" src="https://www.youtube.com/embed/lJc8CJj4CII" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

人工智慧是什麼？  

<iframe width="560" height="315" src="https://www.youtube.com/embed/FsLZIcxflhI" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>


## 傳統支付母湯喔~新潮流行動支付

回想一下，你是否曾經因為買東西卻發現身上現金不夠，而必須到附近找便利商店領錢；或者是結完帳找了一大堆零錢把自己搞得手忙腳亂；又或者皮包裡有各式各樣的卡片，但要搭公車卻找不到悠遊卡的經驗。

不過放心，這種情況未來只會越來越罕見，隨著今年三大品牌手機支付(Apple Pay、Samsung Pay、Android Pay)進軍台灣市場，行動支付市場戰火已狼煙四起，大家都想分一杯羹，那麼我們就來認識什麼是行動支付吧。

行動支付簡單來講就是在不需要使用現金或信用卡的狀況下，運用行動裝置進行付款。然而行動支付市場究竟有多誘人呢？首先，廠商可以透過消費者的消費數據進行分析，提供更確切的行銷服務；另外，除了每筆交易手續費的累積外，有些滯留在平台上的資金可能帶來更多利益，這也就說明近年行動支付如雨後春筍般出現的原因。

行動支付又有分幾種不同種類，除了上述所提到的手機支付外，另外還有透過與店家合作的第三方支付如Line Pay、街口支付…，以及透過先儲值的電子支付是很多遊戲業者運用的方式，如歐富寶、橘子支……。

接著我們來看一些數據了解一下行動支付的未來趨勢吧，根據Juniper Research 報告指出，全球數位支付在今年將成長14%，達到3.9兆美元，這究竟是多大的一塊市場呢?最新的資料顯示，2017年全球前250大零售商總營收為4.3兆美金，而行動支付與之距離正在拉近，且行動支付目前還是屬於未完全普及的狀況；接著我們來看看行動支付在台灣的市場潛力，根據IDC，去年台灣民間消費總額大約為9兆美元，使用電子貨幣佔3兆元，而根據金管會提出在2020年電子支付為52%的比例計算，台灣還潛在1.5兆美元的市場，這也難怪行動支付在台灣或者世界各地競爭越演越烈。

無論身處何處，行動支付勢必成為未來的趨勢，透過與人工智慧的結合，這塊金融科技領域將勢不可擋，如對行動支付有興趣的可以參考以下連結，對人工智慧帶來的影響，也歡迎閱讀我們"科幻小說般的智慧生活型態"一文。

### 關於行動支付的小影片: {-}

[行動支付優缺點](https://www.youtube.com/watch?v=fDWZs1IfJ48)

[Apple pay是如何運作的](https://www.youtube.com/watch?v=ksFXEY6P_ec)

[中國的行動支付運作發展](https://www.youtube.com/watch?v=-Cx0lFYq-q4)


### 關於行動支付更深入文章: {-}

[關於四大行動支付詳談](https://technews.tw/2017/06/01/top-4-mobile-pay-in-tw/)

[了解行動支付間的差異](https://technews.tw/2017/06/15/mobile-wallet-issues/)

## 不怕被邊緣，只怕沒資源 

大家好，這裡是鴨肉。

先說好，在大家聽完小生悲慘的經歷前，小生是不會開始介紹「創意集資」的。
  
從小，小生就知道自己沒人愛，是班上的邊緣人，不管有什麼點子，都沒有人會支持小生。曾經，媽媽問小生未來想找什麼出路，那時小生不假思索地大喊：「我要開冰淇淋店。」結果媽媽馬上轉過頭說：「我不想討論這種話題。」從那天起，小生就再也不敢向別人談論自己的夢想了。

不要可憐小生，小生已經沒救了，小生就要去當兵然後考公職了。但你們，你們不同，你們是懷抱夢想與希望的年輕人。現在時代變了，只要你們能為你的夢想寫一份企劃，並告訴大家為什麼要贊助你，把自己最好最熱情的一面展現給這個世界，大家肯定也不會吝嗇給予你們幫助與支持的。
    
以下就要跟大家簡略介紹集資的一個方向與概念。
  
集資的簡略流程：

首先，你得先有一個好的idea，還有不怕挫折的勇氣。你就可以開始向集資網站註冊，接著放上你的企劃給民眾參考了。在一般的情況下，你必須預設一個集資門檻，也就是當集資金額達到此目標，這個計畫才會成行，民眾也才會實際收到成品。一旦資金達到門檻後，就要開始動工啦，定期回報進度也很重要喔。當然在之中，你還可以設定額外獎勵，只要到更高的金額，就可以再免費回饋給消費者，藉此鼓勵更多人支持你。
集資的好處：

除了向民眾募資外，集資其實有很大一部份的企劃不一定是真的缺乏資金，而是在向市場試水溫，確認市場的接受度。比起製造出一批沒人買的商品，先確認好需求再製造反而能降低風險。再者，集資網站本身帶有一種話題性，這是一種廣告效果，可以刺激消費者購買。
  
就算到最後未達集資門檻，也不會因此真的虧損什麼，反而能學習到寶貴的經驗。
    
檢視評估自己的企劃：

在決定要集資前，還請先評估自己的計劃是否有可行性，會不會眼高手低？或錯估市場的接受度？
以下有幾個問題可以先問問自己：
  
１．市場上是否已經有同質性高的商品？
      
２．推行的產品或計畫，會不會有難以克服的技術問題？
      
３．是否未達到一個相對高的金額就無法成行（例：５００萬）？
      
４．受限於特定的使用族群。

５．集資到預定出貨的時間超過一年。

好的，看到這邊，相信你們已經認知到自己跟小生不一樣，是充滿可能性的個體了
最後跟小生一起念：「不怕被邊緣，只怕沒資源。」再念一次，「不怕被邊緣，只怕沒資源。」
全體稍息後不敬禮解散。

臺灣的集資平台

嘖嘖：https://www.zeczec.com/
  
FlyingV：https://www.flyingv.cc/
  
國外的集資平台

kickstarter：https://www.kickstarter.com/
  
群眾集資顧問公司

貝殼放大：https://www.backer-founder.com/

